<a href="https://colab.research.google.com/github/reddit323/iausepython/blob/main/school_ia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

df_vid=pd.read_csv("/content/ai_student_impact_dataset (1).csv")

df_vid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB

In [ ]:
df_vid

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.310,Copywriting/Drafting,Beginner,1,True,8.130,5,Allowed_With_Citation,6,2.393,86.440,High
1,100002,Medical,Junior,3.821,1.120,Ideation,Advanced,5,False,16.650,3,Allowed_With_Citation,9,3.696,69.390,Low
2,100003,Business,Freshman,3.398,21.260,Summarizing_Reading,Beginner,2,False,10.350,5,Strict_Ban,9,3.499,73.930,Medium
3,100004,Business,Senior,3.789,1.820,Copywriting/Drafting,Intermediate,4,False,15.230,2,Allowed_With_Citation,2,4.000,63.580,Medium
4,100005,STEM,Sophomore,3.635,9.290,Debugging/Troubleshooting,Advanced,4,False,12.550,4,Allowed_With_Citation,4,3.798,100.000,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.160,Copywriting/Drafting,Beginner,2,False,13.360,2,Allowed_With_Citation,2,3.584,66.160,High
49996,149997,STEM,Senior,2.870,2.510,Copywriting/Drafting,Intermediate,1,False,4.670,3,Actively_Encouraged,3,3.096,81.620,Medium
49997,149998,Business,Senior,3.177,15.870,Summarizing_Reading,Advanced,5,True,3.920,4,Allowed_With_Citation,5,3.605,97.210,High
49998,149999,Business,Junior,3.398,19.910,Debugging/Troubleshooting,Intermediate,5,False,7.100,5,Allowed_With_Citation,3,3.527,84.120,Medium
49999,150000,Arts,Sophomore,3.242,3.300,Copywriting/Drafting,Beginner,1,False,3.930,2,Allowed_With_Citation,6,3.261,76.160,Low

In [ ]:
df_vid['gpa before ia and after']=df_vid['Post_Semester_GPA']+df_vid['Pre_Semester_GPA']

In [ ]:
df_vid

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level,gpa before ia and after
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High,4.811
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low,7.517
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium,6.897
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium,7.789
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium,7.433
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High,6.483
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium,5.966
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High,6.782
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium,6.925
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low,6.503

In [ ]:

(df_vid['Major_Category'].value_counts(normalize=True)*100).rename("category uses of ia").reset_index()

  Major_Category  category uses of ia
0           STEM               30.118
1       Business               25.076
2     Humanities               19.988
3        Medical               12.952
4           Arts               11.866

In [ ]:
df_vid.groupby("Major_Category")['gpa before ia and after'].sum().reset_index()

  Major_Category  gpa before ia and after
0           Arts                38507.983
1       Business                81219.223
2     Humanities                64897.788
3        Medical                42125.973
4           STEM                98019.121

In [ ]:
df_vid['Student_ID'].value_counts(dropna=False)

Student_ID
149984    1
149983    1
149982    1
149981    1
149980    1
         ..
100005    1
100004    1
100003    1
100002    1
100001    1
Name: count, Length: 50000, dtype: int64

In [ ]:
df_vid['Primary_Use_Case'].value_counts(dropna=False)

Primary_Use_Case
Debugging/Troubleshooting    12295
Copywriting/Drafting         12011
Ideation                     10721
Summarizing_Reading           8633
Direct_Answer_Generation      6340
Name: count, dtype: int64